### ISSUE TITLE
Test YAML file

### ISSUE THREAD

**Issue by jonatasbaldin** [jonatasbaldin/python-community-map#26]
If we don't have the data necessary in the file, we can break the Google Maps API.

Let's add some test to the YAML file, such a schema test or something like it.

**Comment by stsewd** [comment]
We can use [yamale](https://github.com/23andMe/Yamale) is very simple and it's written in python.

**Comment by jonatasbaldin** [comment]
Thanks for the tip @stsewd, but since I'm gonna use Node to test the functions that create the map, I went with the Node environment for testing!

Also, closed with #38
