### ISSUE TITLE
Display community name in bubble

### ISSUE THREAD

**Issue by NiklasMM** [jonatasbaldin/python-community-map#3]
The bubble that appears when clicking on a marker now only shows the URL. 

It would be cool if it at least also displayed the community name. With more and more communities being added things could become confusing otherwise.

**Comment by jonatasbaldin** [comment]
Ahhhh, just broke it with the last commit 😿 will try to revert now (but I'm on the road). If you could open a PR to revert the last commit, I'd appreciate 🐍

**Comment by jonatasbaldin** [comment]
Fixed!

**Comment by jonatasbaldin** [comment]
Hahah, thanks for the issue tho!
