### ISSUE TITLE
Add more info in the communities card

### ISSUE THREAD

**Issue by l2radamanthys** [jonatasbaldin/python-community-map#48]
Add an optional parameters:
- short description of comunity 
- comunity avatar
to show in modal.

**Comment by FedericoJurio** [comment]
Another improve that it would be great to add to the modal would be display social media icons for twitter, telegram, etc.

**Comment by jonatasbaldin** [comment]
Hey mates!

So yeah, that'd be nice, but it adds more need for information when adding a new community, and ppl may feel overwhelmed (you know people these days hahah)

Also, some of the communities may have just a small subset of information, creating cards in different formats (this may not be an issue tho).

Anyway, we can try to design a new card to accommodate more info. @humrochagf had some ideas on that, I guess. If you have any ideas, lmk :D I'll try to do some as well :)

**Comment by jonatasbaldin** [comment]
@l2radamanthys 	I changed the title of the issue to better reflect this discussion

**Comment by l2radamanthys** [comment]
@jonatasbaldin  I added a [pull request](https://github.com/jonatasbaldin/python-community-map/pull/49) for this requeriments to avatar and short description.

preview of this change 
[preview](https://prnt.sc/lbaixa)

**Comment by jonatasbaldin** [comment]
Hey, I opened #59 for that too :D

**Comment by jonatasbaldin** [comment]
Fixed on #59 merge.
