### ISSUE TITLE
Create Pull Request and Issue templates?

### ISSUE THREAD

**Issue by jtemporal** [jonatasbaldin/python-community-map#52]
would be nice to have [pr and issue templates](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/)?

I believe that would help new comers to contribute

**Comment by jonatasbaldin** [comment]
Yes, that's a good one :D

**Comment by jonatasbaldin** [comment]
For PR the info seems pretty straightforward when adding a community, for example.

Issues I have no idea what we could use 🤷‍♀️ hahah

Any ideas?

**Comment by jonatasbaldin** [comment]
hey @jtemporal, added a PR template and some info on the #55!

I think the issues can still be very random, so I won't create a template for that now, but maybe one day

thanks ❤️

**Comment by jtemporal** [comment]
> I think the issues can still be very random

I thought so too... that's why there's a question mark there lol 

great work on #55 :tada:
