### ISSUE TITLE
Import partial data from @PKpacheco's comunidades-python-latam?

### ISSUE THREAD

**Issue by ayharano** [jonatasbaldin/python-community-map#53]
In https://github.com/PKpacheco/comunidades-python-latam there are data from LatAm community but without geographical data.

Suggestion to import could be something like

- [ ] Check if listed communities are up-to-date and active
- [ ] Default latitude/longitude data based on city's downtown / state|country's capital?

**Comment by jonatasbaldin** [comment]
So, about data scrapping, I'm gonna paste an answer to another issue (gonna put this on the README as well).

> Actually I want to avoid doing scrapping, because I'd like to see people adding the communities they belong to. I think it creates a better sense of "putting yourself in the map" of some sorts and also incentivise people to contribute to open source :)

Does it make sense to you? It's just a feeling that I have

**Comment by ayharano** [comment]
Yes, it does a lot of sense to me. Organic input seems very fit for communities, especially Python's ;)

Including into README is a neat idea to avoid opening this kind of issue again and again.

Closing this issue as its reasoning was clearly explained.
